version: '3'

services:
  web:
    image: calculator:0.0.1
    build: .
    command: gunicorn calculator.calculator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/calculator/static
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: